name: Daily Blog Upload

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  generate-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Debug secret
        run: |
          echo "FIREBASE_SERVICE_ACCOUNT_JSON is set: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON != '' }}"

      - name: Run blog generation script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: node generateBlog.js
